# Generated by Django 5.2.14 on 2026-06-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=67, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=67, verbose_name='телефон')),
                ('email', models.EmailField(max_length=67, verbose_name='электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=67, verbose_name='название техники')),
                ('category', models.CharField(max_length=67, verbose_name='категория техники')),
                ('description', models.TextField(verbose_name='описание')),
                ('price_per_day', models.FloatField(verbose_name='стоимость аренды за сутки')),
                ('serial_number', models.CharField(max_length=30, verbose_name='серийный номер')),
                ('is_available', models.BooleanField(verbose_name='доступность техники')),
                ('created_at', models.CharField(max_length=67, verbose_name='дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=67, verbose_name='название техники')),
                ('customer', models.CharField(max_length=67, verbose_name='клиент')),
                ('start_date', models.DateTimeField(verbose_name='дата начала аренды')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания аренды')),
                ('total_price', models.FloatField(verbose_name='итоговая стоимость')),
                ('status_active', models.CharField(choices=[('active', 'Доступна'), ('finished', 'законченный'), ('cancelled', 'отменен')], default='active', max_length=15, verbose_name='доступность техники')),
                ('created_at', models.DateField(verbose_name='дата оформления')),
            ],
        ),
    ]
